const activities_free = [
  {
    name_lat: "Makšķerēšana, vispārēji",
    name_eng: "Fishing, general",
    name_ita: "Pesca, generale",
    name_esp: "Pesca, generales",
    name_fra: "Pêche, général",
    name_vtn: "Câu cá, tổng hợp",
    met: 3.5,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Makšķerēšana, krabju makšķerēšana",
    name_eng: "Fishing, crab fishing",
    name_ita: "Pesca, pesca del granchio",
    name_esp: "Pesca, pesca de cangrejos",
    name_fra: "Pêche, pêche au crabe",
    name_vtn: "Câu cá, câu cua",
    met: 4.5,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Makšķerēšana, zivju ķeršana ar rokām",
    name_eng: "Fishing, catching fish with hands",
    name_ita: "Pesca, cattura del pesce con le mani",
    name_esp: "Pesca, captura de peces con las manos.",
    name_fra: "Pêcher, attraper du poisson avec les mains",
    name_vtn: "Câu cá, bắt cá bằng tay",
    met: 4,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Ar makšķerēšanu saistīti, rakšanas tārpi, ar lāpstu",
    name_eng: "Fishing related, digging worms, with shovel",
    name_ita: "Legati alla pesca, scavatori di vermi, con pala",
    name_esp: "Relacionado con la pesca, cavando gusanos, con pala",
    name_fra: "Liés à la pêche, creuser des vers, avec une pelle",
    name_vtn: "Liên quan đến câu cá, đào giun, bằng xẻng",
    met: 4.3,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Makšķerēšana no upes krasta un pastaigas",
    name_eng: "Fishing from river bank and walking",
    name_ita: "Pesca dalla riva del fiume e passeggiate",
    name_esp: "Pesca desde la orilla del río y caminata",
    name_fra: "Pêche au bord de la rivière et promenade",
    name_vtn: "Câu cá từ bờ sông và đi bộ",
    met: 4,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Makšķerēšana no laivas vai kanoe, sēžot",
    name_eng: "Fishing from boat or canoe, sitting",
    name_ita: "Pescare dalla barca o dalla canoa, seduti",
    name_esp: "Pesca desde barco o canoa, sentado",
    name_fra: "Pêcher en bateau ou en canoë, assis",
    name_vtn: "Câu cá từ thuyền hoặc ca nô, ngồi",
    met: 2,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Makšķerēšana upes krastā, stāvus",
    name_eng: "Fishing from river bank, standing",
    name_ita: "Pesca dalla riva del fiume, in piedi",
    name_esp: "Pesca desde la orilla del río, de pie",
    name_fra: "Pêche au bord de la rivière, debout",
    name_vtn: "Câu cá từ bờ sông, đứng",
    met: 3.5,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Makšķerēšana straumē, bridējputnēs",
    name_eng: "Fishing in stream, in waders",
    name_ita: "Pesca in torrente, in trampolieri",
    name_esp: "Pesca en arroyo, en botas",
    name_fra: "Pêche en ruisseau, en cuissardes",
    name_vtn: "Câu cá ở suối, ở lội",
    met: 6,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Makšķerēšana, ledus, sēdēšana",
    name_eng: "Fishing, ice, sitting",
    name_ita: "Pesca, ghiaccio, seduta",
    name_esp: "Pesca, hielo, sentado",
    name_fra: "Pêche, glace, assis",
    name_vtn: "Câu cá, băng, ngồi",
    met: 2,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Makšķerēšana, skriešana vai rindā, stāvēšana, vispārēja",
    name_eng: "Fishing, jog or line, standing, general",
    name_ita: "Pesca, jogging o lenza, in piedi, generale",
    name_esp: "Pesca, trote o línea, de pie, general",
    name_fra: "Pêche, jogging ou ligne, debout, général",
    name_vtn: "Câu cá, chạy bộ hoặc xếp hàng, đứng, nói chung",
    met: 1.8,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Makšķerēšana, iegremdējamais tīkls, tīkla uzstādīšana un zivju izņemšana, vispārīgi",
    name_eng: "Fishing, dip net, setting net and retrieving fish, general",
    name_ita: "Pesca, guadino, guadino e recupero del pesce, in generale",
    name_esp: "Pesca, trasmallo, calado de redes y recuperación de peces, general",
    name_fra: "Pêche, épuisette, calage et récupération du poisson, général",
    name_vtn: "Câu cá, thả lưới, giăng lưới và vớt cá nói chung",
    met: 3.5,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Makšķerēšana, ielikt tīklu, tīklu izlikšana un zivju izņemšana, vispārīgi",
    name_eng: "Fishing, set net, setting net and retrieving fish, general",
    name_ita: "Pesca, calamaio, calamaio e recupero del pesce, generale",
    name_esp: "Pesca, calado, calado de redes y recuperación de peces, general",
    name_fra: "Pêche, filet fixe, filet de pose et récupération du poisson, général",
    name_vtn: "Câu cá, giăng lưới, giăng lưới và vớt cá, nói chung",
    met: 3.8,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Makšķerēšana, makšķerēšanas ritenis, tīkla uzstādīšana un zivju izņemšana, vispārīgi",
    name_eng: "Fishing, fishing wheel, setting net and retrieving fish, general",
    name_ita: "Pesca, ruota da pesca, rete da pesca e recupero del pesce, generale",
    name_esp: "Pesca, rueda de pesca, colocación de redes y recuperación de peces, general",
    name_fra: "Pêche, roue à pêche, filet de pêche et récupération du poisson, général",
    name_vtn: "Câu cá, bánh xe câu, giăng lưới và vớt cá, nói chung",
    met: 3,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Makšķerēšana ar šķēpu, stāvus",
    name_eng: "Fishing with a spear, standing",
    name_ita: "Pesca con una lancia, in piedi",
    name_esp: "Pesca con lanza, de pie",
    name_fra: "Pêche au harpon, debout",
    name_vtn: "Câu cá bằng giáo, đứng",
    met: 2.3,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Medības, loks un bultas vai arbalets",
    name_eng: "Hunting, bow and arrow, or crossbow",
    name_ita: "Caccia, arco e frecce o balestra",
    name_esp: "Caza, arco y flecha o ballesta",
    name_fra: "Chasse, arc et flèche ou arbalète",
    name_vtn: "Săn bắn, cung tên, hoặc nỏ",
    met: 2.5,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Medības, brieži, aļņi, lielie medījumi",
    name_eng: "Hunting, deer, elk, large game",
    name_ita: "Caccia, cervi, alci, selvaggina grossa",
    name_esp: "Caza, ciervos, alces, caza mayor",
    name_fra: "Chasse, cerf, wapiti, gros gibier",
    name_vtn: "Săn bắn, nai, nai sừng tấm, trò chơi lớn",
    met: 6,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Lielo medījumu medības, liemeņa vilkšana",
    name_eng: "Hunting large game, dragging carcass",
    name_ita: "A caccia di grossa selvaggina, trascinando carcasse",
    name_esp: "Caza mayor, arrastre de cadáveres",
    name_fra: "Chasse au gros gibier, traînage de carcasse",
    name_vtn: "Trò chơi săn lớn, kéo xác",
    met: 11.3,
    cluster: 5,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Lielu jūras dzīvnieku medības",
    name_eng: "Hunting large marine animals",
    name_ita: "A caccia di grandi animali marini",
    name_esp: "Caza de grandes animales marinos",
    name_fra: "Chasse aux grands animaux marins",
    name_vtn: "Săn bắt động vật biển lớn",
    met: 4,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Lielo medījumu medības, no medību stenda, ierobežota pastaiga",
    name_eng: "Hunting large game, from a hunting stand, limited walking",
    name_ita: "Caccia alla grande selvaggina, da un posto di caccia, camminata limitata",
    name_esp: "Caza mayor, desde un puesto de caza, caminata limitada",
    name_fra: "Chasse au gros gibier, depuis un poste de chasse, marche limitée",
    name_vtn: "Trò chơi săn bắn lớn, từ chỗ săn bắn, đi lại hạn chế",
    met: 2.5,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Lielo medījumu medības no automašīnas, lidmašīnas vai laivas",
    name_eng: "Hunting large game from a car, plane, or boat",
    name_ita: "Cacciare selvaggina di grandi dimensioni da un'auto, un aereo o una barca",
    name_esp: "Caza mayor desde un coche, avión o barco",
    name_fra: "Chasse au gros gibier depuis une voiture, un avion ou un bateau",
    name_vtn: "Săn trò chơi lớn từ ô tô, máy bay hoặc thuyền",
    met: 2,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Medības, pīle, brišana",
    name_eng: "Hunting, duck, wading",
    name_ita: "Caccia, anatra, guado",
    name_esp: "Caza, pato, vadeo",
    name_fra: "Chasse, canard, pataugeoire",
    name_vtn: "Săn bắn, vịt, lội nước",
    met: 2.5,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Medības, lidojoša lapsa, vāvere",
    name_eng: "Hunting, flying fox, squirrel",
    name_ita: "Caccia, volpe volante, scoiattolo",
    name_esp: "Caza, zorro volador, ardilla",
    name_fra: "Chasse, renard volant, écureuil",
    name_vtn: "Săn bắn, cáo bay, sóc",
    met: 3,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Medības, vispārēji",
    name_eng: "Hunting, general",
    name_ita: "Caccia, generale",
    name_esp: "Caza, general",
    name_fra: "Chasse, général",
    name_vtn: "Săn bắn, nói chung",
    met: 5,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Medības, fazāni vai rubeņi",
    name_eng: "Hunting, pheasants or grouse",
    name_ita: "Caccia, fagiani o galli cedroni",
    name_esp: "Caza, faisanes o urogallos",
    name_fra: "Chasse, faisans ou tétras",
    name_vtn: "Săn bắn, gà lôi hoặc gà gô",
    met: 6,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Medības, putni",
    name_eng: "Hunting, birds",
    name_ita: "Caccia, uccelli",
    name_esp: "caza, pájaros",
    name_fra: "Chasse, oiseaux",
    name_vtn: "Săn bắn, chim",
    met: 3.3,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Medības, trusis, vāvere, prēriju cālis, jenots, mazie medījumi (Taylor Code 690)",
    name_eng: "Hunting, rabbit, squirrel, prairie chick, raccoon, small game (Taylor Code 690)",
    name_ita: "Caccia, coniglio, scoiattolo, pulcino della prateria, procione, piccola selvaggina (Codice Taylor 690)",
    name_esp: "Caza, conejo, ardilla, pollito de pradera, mapache, caza menor (Código Taylor 690)",
    name_fra: "Chasse, lapin, écureuil, poussin des prairies, raton laveur, petit gibier (Taylor Code 690)",
    name_vtn: "Săn bắn, thỏ, sóc, gà đồng cỏ, gấu trúc, trò chơi nhỏ (Taylor Code 690)",
    met: 5,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Medības, cūkas, savvaļas",
    name_eng: "Hunting, pigs, wild",
    name_ita: "Caccia, maiali, selvatici",
    name_esp: "Caza, cerdos, salvaje",
    name_fra: "Chasse, cochons, sauvage",
    name_vtn: "Săn bắn, lợn, hoang dã",
    met: 3.3,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Slazdu spēle, ģenerālis",
    name_eng: "Trapping game, general",
    name_ita: "Gioco di trappole, generale",
    name_esp: "Juego de captura, general",
    name_fra: "Jeu de piégeage, général",
    name_vtn: "Trò chơi bẫy, nói chung",
    met: 2,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Medības, pārgājieni ar medību rīkiem",
    name_eng: "Hunting, hiking with hunting gear",
    name_ita: "Caccia, escursionismo con attrezzatura da caccia",
    name_esp: "Caza, senderismo con equipo de caza.",
    name_fra: "Chasse, randonnée avec matériel de chasse",
    name_vtn: "Săn bắn, đi bộ đường dài với dụng cụ săn bắn",
    met: 9.5,
    cluster: 4,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Šaušana ar pistoli vai slazda šaušana, stāvus",
    name_eng: "Pistol shooting or trap shooting, standing",
    name_ita: "Tiro con la pistola o tiro al piattello, in piedi",
    name_esp: "Tiro con pistola o tiro al plato, de pie",
    name_fra: "Tir au pistolet ou tir au piège, debout",
    name_vtn: "Bắn súng lục hoặc bắn bẫy, đứng",
    met: 2.5,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Šaušanas vingrinājumi, šaušana, guļus",
    name_eng: "Rifle exercises, shooting, lying down",
    name_ita: "Esercizi con il fucile, tiro, sdraiato",
    name_esp: "Ejercicios de rifle, tiro, acostado",
    name_fra: "Exercices de carabine, tir, couché",
    name_vtn: "Bài tập súng trường, bắn súng, nằm xuống",
    met: 2.3,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Šaušanas vingrinājumi, šaušana, ceļos vai stāvēšana",
    name_eng: "Rifle exercises, shooting, kneeling or standing",
    name_ita: "Esercizi con il fucile, tiro, in ginocchio o in piedi",
    name_esp: "Ejercicios de rifle, tiro, de rodillas o de pie",
    name_fra: "Exercices de carabine, tir, à genoux ou debout",
    name_vtn: "Bài tập súng trường, bắn súng, quỳ hoặc đứng",
    met: 2.5,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Klusi guļot, skatās televizoru",
    name_eng: "Lying quietly and watching television",
    name_ita: "Sdraiato tranquillamente e guardando la televisione",
    name_esp: "Tumbado tranquilamente y viendo la televisión.",
    name_fra: "Allongé tranquillement et regardant la télévision",
    name_vtn: "Nằm yên lặng và xem tivi",
    met: 1,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Klusi guļot, neko nedarot, guļot nomodā gultā, klausoties mūziku (nerunājot vai nelasot)",
    name_eng: "Lying quietly, doing nothing, lying in bed awake, listening to music (not talking or reading)",
    name_ita: "Sdraiato in silenzio, senza fare nulla, sdraiato a letto sveglio, ascoltando musica (senza parlare o leggere)",
    name_esp: "Acostado en silencio, sin hacer nada, acostado en la cama despierto, escuchando música (sin hablar ni leer)",
    name_fra: "Allongé tranquillement, ne faisant rien, allongé dans son lit éveillé, écoutant de la musique (sans parler ni lire)",
    name_vtn: "Nằm yên, không làm gì, nằm trên giường tỉnh táo, nghe nhạc (không nói chuyện hoặc đọc sách)",
    met: 1.3,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Mierīgi sēžot un skatoties televizoru",
    name_eng: "Sitting quietly and watching television",
    name_ita: "Seduto in silenzio e guardando la televisione",
    name_esp: "Sentado en silencio y viendo la televisión",
    name_fra: "Assis tranquillement et regardant la télévision",
    name_vtn: "Ngồi lặng lẽ và xem tivi",
    met: 1.3,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Mierīgi sēž, vispārēji",
    name_eng: "Sitting quietly, general",
    name_ita: "Seduto in silenzio, generale",
    name_esp: "Sentado en silencio, general",
    name_fra: "Assis tranquillement, général",
    name_vtn: "Ngồi lặng lẽ, tướng quân",
    met: 1.3,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Klusi sēžot, grozoties, vispārīgi, vicinot rokas",
    name_eng: "Sitting quietly, fidgeting, general, fidgeting hands",
    name_ita: "Seduto in silenzio, agitandosi, generale, agitando le mani",
    name_esp: "Sentado en silencio, inquieto, general, manos inquietas",
    name_fra: "Assis tranquillement, agité, général, mains agitées",
    name_vtn: "Ngồi thẫn thờ, bồn chồn, chung chung, bồn chồn tay",
    met: 1.5,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Sēžot, kustinot kājas",
    name_eng: "Sitting, fidgeting feet",
    name_ita: "Piedi seduti e agitati",
    name_esp: "Sentado, pies inquietos",
    name_fra: "Assis, pieds agités",
    name_vtn: "Ngồi mỏi chân",
    met: 1.8,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Sēž, smēķē",
    name_eng: "Sitting, smoking",
    name_ita: "Seduto, fumando",
    name_esp: "sentado, fumando",
    name_fra: "Assis, fumer",
    name_vtn: "Ngồi, hút thuốc",
    met: 1.3,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Sēžot, klausoties mūziku (nevis runājot vai lasot) vai skatoties filmu teātrī",
    name_eng: "Sitting, listening to music (not talking or reading) or watching a movie in a theater",
    name_ita: "Sedersi, ascoltare musica (non parlare o leggere) o guardare un film in un teatro",
    name_esp: "Sentado, escuchando música (sin hablar ni leer) o viendo una película en un cine",
    name_fra: "Être assis, écouter de la musique (sans parler ni lire) ou regarder un film au cinéma",
    name_vtn: "Ngồi, nghe nhạc (không nói hoặc đọc) hoặc xem phim trong rạp",
    met: 1.5,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Sēžu pie rakstāmgalda, atspiedu galvu rokās",
    name_eng: "Sitting at a desk, resting head in hands",
    name_ita: "Seduto alla scrivania, con la testa tra le mani",
    name_esp: "Sentado en un escritorio, apoyando la cabeza en las manos",
    name_fra: "Assis à un bureau, la tête dans les mains",
    name_vtn: "Ngồi ở bàn làm việc, tựa đầu vào tay",
    met: 1.3,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Guļot",
    name_eng: "Sleeping",
    name_ita: "Dormire",
    name_esp: "Durmiendo",
    name_fra: "Dormant",
    name_vtn: "Đang ngủ",
    met: 0.95,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Klusi stāvot, stāvot rindā",
    name_eng: "Standing quietly, standing in a line",
    name_ita: "In piedi in silenzio, in fila",
    name_esp: "De pie en silencio, de pie en una línea",
    name_fra: "Debout tranquillement, debout en ligne",
    name_vtn: "Đứng lặng lẽ, đứng thành một hàng",
    met: 1.3,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Stāvēt, rosīties",
    name_eng: "Standing, fidgeting",
    name_ita: "In piedi, irrequieto",
    name_esp: "De pie, inquieto",
    name_fra: "Debout, agité",
    name_vtn: "Đứng, bồn chồn",
    met: 1.8,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Guļus, rakstīšana",
    name_eng: "Reclining, writing",
    name_ita: "Sdraiarsi, scrivere",
    name_esp: "Reclinado, escribiendo",
    name_fra: "S'allonger, écrire",
    name_vtn: "Nằm, viết",
    met: 1.3,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Guļus, runājot vai runājot pa tālruni",
    name_eng: "Reclining, talking or talking on phone",
    name_ita: "Sdraiato, parlando o parlando al telefono",
    name_esp: "Reclinado, hablando o hablando por teléfono",
    name_fra: "S'allonger, parler ou parler au téléphone",
    name_vtn: "Nằm, nói chuyện hoặc nói chuyện trên điện thoại",
    met: 1.3,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Guļus, lasīšana",
    name_eng: "Reclining, reading",
    name_ita: "Sdraiato, lettura",
    name_esp: "Reclinado, leyendo",
    name_fra: "Se coucher, lire",
    name_vtn: "Nằm thư giãn, đọc sách",
    met: 1.3,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Meditējot",
    name_eng: "Meditating",
    name_ita: "Meditando",
    name_esp: "meditando",
    name_fra: "Méditer",
    name_vtn: "ngồi thiền",
    met: 1,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Kokmateriālu nešana, iekraušana vai sakraušana, zāģmateriālu iekraušana/izkraušana vai pārvadāšana, viegla vai mērena piepūle",
    name_eng: "Carrying, loading or stacking wood, loading/unloading or carrying lumber, light-to-moderate effort",
    name_ita: "Trasportare, caricare o accatastare legna, caricare/scaricare o trasportare legname, sforzo da leggero a moderato",
    name_esp: "Transporte, carga o apilamiento de madera, carga/descarga o transporte de madera, esfuerzo ligero a moderado",
    name_fra: "Transporter, charger ou empiler du bois, charger/décharger ou transporter du bois, effort léger à modéré",
    name_vtn: "Khuân vác, chất hoặc xếp gỗ, chất/dỡ hoặc khuân vác gỗ, gắng sức từ nhẹ đến trung bình",
    met: 3.3,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Kokmateriālu nešana, iekraušana vai sakraušana, zāģmateriālu iekraušana/izkraušana vai pārvadāšana",
    name_eng: "Carrying, loading or stacking wood, loading/unloading or carrying lumber",
    name_ita: "Trasporto, carico o accatastamento legna, carico/scarico o trasporto legname",
    name_esp: "Transporte, carga o apilamiento de madera, carga/descarga o transporte de madera",
    name_fra: "Transporter, charger ou empiler du bois, charger/décharger ou transporter du bois",
    name_vtn: "Bốc vác, xếp hoặc xếp gỗ, xếp/dỡ hoặc khuân vác gỗ",
    met: 5.5,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Malkas skaldīšana, baļķu skaldīšana, mērena piepūle",
    name_eng: "Chopping wood, splitting logs, moderate effort",
    name_ita: "Tagliare legna, spaccare ceppi, sforzo moderato",
    name_esp: "Cortar leña, dividir troncos, esfuerzo moderado",
    name_fra: "Couper du bois, fendre des bûches, effort modéré",
    name_vtn: "Chặt gỗ, chẻ khúc, vừa sức",
    met: 4.5,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Malkas skaldīšana, baļķu skaldīšana, enerģiska piepūle",
    name_eng: "Chopping wood, splitting logs, vigorous effort",
    name_ita: "Tagliare legna, spaccare ceppi, sforzo vigoroso",
    name_esp: "Cortar leña, dividir troncos, esfuerzo vigoroso",
    name_fra: "Couper du bois, fendre des bûches, effort vigoureux",
    name_vtn: "Chặt gỗ, chẻ củi, tinh tấn",
    met: 6.3,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Otas tīrīšana, dārza retināšana, mērena piepūle",
    name_eng: "Clearing light brush, thinning garden, moderate effort",
    name_ita: "Spazzolatura leggera, diradamento del giardino, sforzo moderato",
    name_esp: "Limpieza de matorrales ligeros, raleo de jardines, esfuerzo moderado",
    name_fra: "Débroussaillage des broussailles légères, éclaircissage du jardin, effort modéré",
    name_vtn: "Phát quang nhẹ, tỉa thưa vườn, công sức vừa phải",
    met: 3.5,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Krūmu/zemes, zemes tīrīšana, zaru vilkšana, ķerras darbi, enerģiska piepūle",
    name_eng: "Clearing brush/land, undergrowth, or ground, hauling branches, wheelbarrow chores, vigorous effort",
    name_ita: "Rimozione di arbusti/terra, sottobosco o terreno, trasporto di rami, lavori con carriola, sforzi vigorosi",
    name_esp: "Limpieza de matorrales/tierra, maleza o suelo, acarreo de ramas, tareas con carretillas, esfuerzo vigoroso",
    name_fra: "Débroussaillage/broussailles, sous-bois ou sol, transport de branches, corvées de brouette, effort vigoureux",
    name_vtn: "Phát quang bụi rậm/đất, bụi rậm hoặc mặt đất, kéo cành cây, làm việc nhà bằng xe cút kít, nỗ lực hết mình",
    met: 6.3,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Smilšu kastes rakšana, smilšu šķūrēšana",
    name_eng: "Digging sandbox, shoveling sand",
    name_ita: "Scavare la sabbiera, spalare la sabbia",
    name_esp: "Cavar caja de arena, palear arena",
    name_fra: "Creuser un bac à sable, pelleter du sable",
    name_vtn: "Đào hố cát, xúc cát",
    met: 5,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Rakšana, darbi ar dakšu, dārza piepildīšana, kompostēšana, viegla vai mērena piepūle",
    name_eng: "Digging, spading, filling garden, composting, light-to-moderate effort",
    name_ita: "Scavare, vangare, riempire il giardino, compostare, sforzo da leggero a moderato",
    name_esp: "Excavación, excavación, relleno del jardín, compostaje, esfuerzo ligero a moderado",
    name_fra: "Creuser, bêcher, remplir le jardin, composter, effort léger à modéré",
    name_vtn: "Đào, xới, lấp vườn, ủ phân, nỗ lực từ nhẹ đến trung bình",
    met: 3.5,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Rakšana, darbi ar dakšu, dārza aizpildīšana, kompozīcija",
    name_eng: "Digging, spading, filling garden, compositing",
    name_ita: "Scavare, vangare, riempire giardini, comporre",
    name_esp: "Excavar, excavar, rellenar el jardín, componer",
    name_fra: "Creuser, bêcher, remplir le jardin, composer",
    name_vtn: "Đào, xới, lấp vườn, vun gốc",
    met: 5,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Rakšana, darbi ar dakšu, dārza aizpildīšana, kompostēšana, enerģiska piepūle",
    name_eng: "Digging, spading, filling garden, composting, vigorous effort",
    name_ita: "Scavare, vangare, riempire il giardino, compostare, uno sforzo vigoroso",
    name_esp: "Cavar, cavar, llenar el jardín, compostaje, esfuerzo vigoroso",
    name_fra: "Creuser, bêcher, remplir le jardin, composter, effort vigoureux",
    name_vtn: "Đào, xới, lấp vườn, ủ phân, nỗ lực hết mình",
    met: 7.8,
    cluster: 4,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Traktora vadīšana",
    name_eng: "Driving tractor",
    name_ita: "Trattore guida",
    name_esp: "Tractor de conducción",
    name_fra: "Conduire un tracteur",
    name_vtn: "lái máy kéo",
    met: 2.8,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Cirst kokus, liela izmēra",
    name_eng: "Felling trees, large size",
    name_ita: "Abbattimento alberi di grandi dimensioni",
    name_esp: "Tala de árboles, gran tamaño",
    name_fra: "Abattage d'arbres de grande taille",
    name_vtn: "Chặt cây, kích thước lớn",
    met: 8.3,
    cluster: 4,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Cirst kokus, maza-vidēja izmēra",
    name_eng: "Felling trees, small-medium size",
    name_ita: "Abbattimento alberi, taglia medio-piccola",
    name_esp: "Tala de árboles, tamaño pequeño-mediano",
    name_fra: "Abattage d'arbres de taille petite à moyenne",
    name_vtn: "Chặt hạ cây vừa và nhỏ",
    met: 5.3,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Dārza darbi ar smagiem elektroinstrumentiem, dārza apstrāde, ķēdes zāģis",
    name_eng: "Gardening with heavy power tools, tilling a garden, chain saw",
    name_ita: "Giardinaggio con utensili elettrici pesanti, coltivare un giardino, motosega",
    name_esp: "Jardinería con herramientas eléctricas pesadas, labrando un jardín, motosierra",
    name_fra: "Jardiner avec des outils électriques lourds, labourer un jardin, scie à chaîne",
    name_vtn: "Làm vườn bằng dụng cụ điện hạng nặng, xới vườn, cưa xích",
    met: 5.8,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Dārzkopība, izmantojot konteinerus, vecāki pieaugušie > 60 gadi",
    name_eng: "Gardening, using containers, older adults > 60 years",
    name_ita: "Giardinaggio, uso di contenitori, anziani > 60 anni",
    name_esp: "Jardinería, uso de contenedores, adultos mayores > 60 años",
    name_fra: "Jardinage, utilisation de contenants, personnes âgées > 60 ans",
    name_vtn: "Làm vườn, sử dụng thùng chứa, người lớn tuổi > 60 tuổi",
    met: 2.3,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Apūdeņošanas kanāli, atvēršanas un aizvēršanas porti",
    name_eng: "Irrigation channels, opening and closing ports",
    name_ita: "Canali di irrigazione, porte di apertura e chiusura",
    name_esp: "Canales de riego, apertura y cierre de puertos",
    name_fra: "Canaux d'irrigation, ports d'ouverture et de fermeture",
    name_vtn: "Kênh tưới, đóng mở cảng",
    met: 4,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Šķembu ieklāšana",
    name_eng: "Laying crushed rock",
    name_ita: "Posa di pietrisco",
    name_esp: "Colocación de roca triturada",
    name_fra: "Pose de pierre concassée",
    name_vtn: "Đặt đá dăm",
    met: 6.3,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Velēnu ieklāšana",
    name_eng: "Laying sod",
    name_ita: "Posa zolla",
    name_esp: "poner césped",
    name_fra: "Pose de gazon",
    name_vtn: "đặt cỏ",
    met: 5,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Zāliena pļaušana, vispārēji",
    name_eng: "Mowing lawn, general",
    name_ita: "Falciare il prato, generale",
    name_esp: "Cortar césped, general",
    name_fra: "Tondre la pelouse, général",
    name_vtn: "Cắt cỏ, nói chung",
    met: 5.5,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Zāliena pļaušana, pļaujmašīna (Taylor Code 550)",
    name_eng: "Mowing lawn, riding mower (Taylor Code 550)",
    name_ita: "Tagliaerba, tosaerba (Taylor Code 550)",
    name_esp: "Cortar césped, tractor cortacésped (Código Taylor 550)",
    name_fra: "Tondre la pelouse, tondeuse autoportée (Taylor Code 550)",
    name_vtn: "Cắt cỏ, cưỡi máy cắt cỏ (Taylor Code 550)",
    met: 2.5,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Zāliena pļaušana, pastaiga, rokas pļāvējs (Taylor Code 570)",
    name_eng: "Mowing lawn, walk, hand mower (Taylor Code 570)",
    name_ita: "Falciatura del prato, marciapiede, tosaerba manuale (codice Taylor 570)",
    name_esp: "Cortar césped, caminar, cortacésped manual (Código Taylor 570)",
    name_fra: "Tondre la pelouse, marcher, tondeuse à main (Taylor Code 570)",
    name_vtn: "Cắt cỏ, đi bộ, máy cắt cỏ cầm tay (Taylor Code 570)",
    met: 6,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Zāliena pļaušana, pastaiga, mehāniskais pļāvējs, mērena vai spēcīga piepūle",
    name_eng: "Mowing lawn, walk, power mower, moderate or vigorous effort",
    name_ita: "Tagliare il prato, camminare, tosaerba, sforzo moderato o intenso",
    name_esp: "Cortar césped, caminar, podadora eléctrica, esfuerzo moderado o vigoroso",
    name_fra: "Tonte de pelouse, promenade, tondeuse électrique, effort modéré ou vigoureux",
    name_vtn: "Cắt cỏ, đi bộ, máy cắt điện, nỗ lực vừa phải hoặc mạnh mẽ",
    met: 5,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Zāliena pļaušana, mehāniskais pļāvējs, viegla vai mērena piepūle",
    name_eng: "Mowing lawn, power mower, light or moderate effort (Taylor Code 590)",
    name_ita: "Taglio del prato, tosaerba, sforzo leggero o moderato (Taylor Code 590)",
    name_esp: "Cortar césped, podadora eléctrica, esfuerzo ligero o moderado (Código Taylor 590)",
    name_fra: "Tondre la pelouse, tondeuse électrique, effort léger ou modéré (Taylor Code 590)",
    name_vtn: "Cắt cỏ, máy cắt điện, nỗ lực nhẹ hoặc vừa phải (Taylor Code 590)",
    met: 4.5,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Darbs ar sniega pūtēju, pastaigas",
    name_eng: "Operating snow blower, walking",
    name_ita: "Fresa da neve in funzione, camminata",
    name_esp: "Soplador de nieve en funcionamiento, caminar",
    name_fra: "Faire fonctionner une souffleuse à neige, marcher",
    name_vtn: "Vận hành máy thổi tuyết, đi bộ",
    met: 2.5,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Stādīšana, stādīšana podos, stādu vai augu pārstādīšana, neliela piepūle",
    name_eng: "Planting, potting, transplanting seedlings or plants, light effort",
    name_ita: "Piantare, invasare, trapiantare piantine o piante, sforzo leggero",
    name_esp: "Plantación, macetas, trasplante de plántulas o plantas, esfuerzo ligero",
    name_fra: "Plantation, rempotage, repiquage de semis ou de plantes, effort léger",
    name_vtn: "Trồng, làm bầu, cấy cây con hoặc cây trồng, ít tốn sức",
    met: 2,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Stādu stadīšana, krūmu, noliekšanos, mērenu piepūli",
    name_eng: "Planting seedlings, shrub, stooping, moderate effort",
    name_ita: "Piantare piantine, arbusti, chinarsi, sforzo moderato",
    name_esp: "Plantar plántulas, arbustos, agacharse, esfuerzo moderado",
    name_fra: "Plantation de semis, arbuste, courbé, effort modéré",
    name_vtn: "Trồng cây con, cây bụi, khom lưng, vừa sức",
    met: 4.3,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Labības stādīšana, noliekšanās, mērena piepūle",
    name_eng: "Planting crops or garden, stooping, moderate effort",
    name_ita: "Piantare colture o giardini, chinarsi, sforzo moderato",
    name_esp: "Siembra de cultivos o jardín, agachado, esfuerzo moderado",
    name_fra: "Planter des cultures ou jardiner, se pencher, effort modéré",
    name_vtn: "Trồng hoa màu hoặc làm vườn, khom lưng, gắng sức vừa phải",
    met: 4.3,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Koku stādīšana",
    name_eng: "Planting trees",
    name_ita: "Piantare alberi",
    name_esp: "Plantando árboles",
    name_fra: "Planter des arbres",
    name_vtn: "Trồng cây",
    met: 4.5,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Zāliena vai lapu grābšana, mērena piepūle",
    name_eng: "Raking lawn or leaves, moderate effort",
    name_ita: "Rastrellare prato o foglie, sforzo moderato",
    name_esp: "Rastrillar el césped o las hojas, esfuerzo moderado",
    name_fra: "Ratisser la pelouse ou les feuilles, effort modéré",
    name_vtn: "Cào cỏ hoặc lá, nỗ lực vừa phải",
    met: 3.8,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Zāliena grābšana",
    name_eng: "Raking lawn (Taylor Code 600)",
    name_ita: "Rastrellatura del prato (Taylor Code 600)",
    name_esp: "Rastrillar el césped (Código Taylor 600)",
    name_fra: "Ratisser la pelouse (Taylor Code 600)",
    name_vtn: "Cào cỏ (Taylor Code 600)",
    met: 4,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Jumta tīrīšana ar sniega lāpstu",
    name_eng: "Raking roof with snow rake",
    name_ita: "Tetto rastrellante con rastrello da neve",
    name_esp: "Techo rastrillado con rastrillo de nieve",
    name_fra: "Toit de ratissage avec râteau à neige",
    name_vtn: "cào mái bằng cào tuyết",
    met: 4,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Braukšana ar sniega pūtēju",
    name_eng: "Riding snow blower",
    name_ita: "Spazzaneve a cavallo",
    name_esp: "Soplador de nieve para montar",
    name_fra: "Souffleuse à neige",
    name_vtn: "Cưỡi máy thổi tuyết",
    met: 3,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Zāles, lapu savākšana",
    name_eng: "Sacking grass, leaves",
    name_ita: "Sacco di erba, foglie",
    name_esp: "Saqueo de hierba, hojas",
    name_fra: "Ramassage de l'herbe, des feuilles",
    name_vtn: "Thu gom cỏ, lá",
    met: 4,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Netīrumu vai dubļu savākšana",
    name_eng: "Shoveling dirt or mud",
    name_ita: "Spalare terra o fango",
    name_esp: "Palear tierra o barro",
    name_fra: "Pelleter de la terre ou de la boue",
    name_vtn: "Xẻng đất hoặc bùn",
    met: 5.5,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Šķūrēt sniegu, ar roku, mēreni piepūli",
    name_eng: "Shoveling snow, by hand, moderate effort",
    name_ita: "Spalare la neve, a mano, sforzo moderato",
    name_esp: "Palear nieve, a mano, esfuerzo moderado",
    name_fra: "Pelleter la neige, à la main, effort modéré",
    name_vtn: "Xẻng tuyết, bằng tay, nỗ lực vừa phải",
    met: 5.3,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Sniega šķūrēšana ar rokām",
    name_eng: "Shovelling snow, by hand (Taylor Code 610)",
    name_ita: "Spalare la neve a mano (Taylor Code 610)",
    name_esp: "Palear nieve, a mano (Código Taylor 610)",
    name_fra: "Pelleter la neige à la main (Taylor Code 610)",
    name_vtn: "Xẻng tuyết bằng tay (Taylor Code 610)",
    met: 6,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Sniega šķūrēšana ar rokām, enerģiska piepūle",
    name_eng: "Shoveling snow, by hand, vigorous effort",
    name_ita: "Spalare la neve, a mano, sforzo vigoroso",
    name_esp: "Palear nieve, a mano, esfuerzo vigoroso",
    name_fra: "Pelleter la neige, à la main, effort vigoureux",
    name_vtn: "Xẻng tuyết, bằng tay, nỗ lực mạnh mẽ",
    met: 7.5,
    cluster: 4,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Krūmu vai koku apgriešana, manuālais griezējs",
    name_eng: "Trimming shrubs or trees, manual cutter",
    name_ita: "Rifilatura di arbusti o alberi, taglierina manuale",
    name_esp: "Recorte de arbustos o árboles, cortadora manual",
    name_fra: "Taille d'arbustes ou d'arbres, coupeuse manuelle",
    name_vtn: "Cắt tỉa cây bụi hoặc cây cối, máy cắt thủ công",
    met: 4,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Krūmu vai koku apgriešana, griezējs, izmantojot lapu pūtēju, malu, mērenu piepūli",
    name_eng: "Trimming shrubs or trees, power cutter, using leaf blower, edge, moderate effort",
    name_ita: "Potatura di arbusti o alberi, mototroncatrice, utilizzo di soffiatore per foglie, spigolo, sforzo moderato",
    name_esp: "Poda de arbustos o árboles, motosierras, uso de soplador de hojas, borde, esfuerzo moderado",
    name_fra: "Taille d'arbustes ou d'arbres, coupeuse électrique, souffleuse à feuilles, bordure, effort modéré",
    name_vtn: "Cắt tỉa cây bụi hoặc cây cối, máy cắt điện, sử dụng máy thổi lá, cạnh, nỗ lực vừa phải",
    met: 3.5,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Staigāšana, mēslojuma uzklāšana vai zāliena sēšana, spiediet aplikatoru",
    name_eng: "Walking, applying fertilizer or seeding a lawn, push applicator",
    name_ita: "Camminare, applicare fertilizzante o seminare un prato, spingere l'applicatore",
    name_esp: "Caminar, aplicar fertilizante o sembrar un césped, empujar el aplicador",
    name_fra: "Marcher, appliquer de l'engrais ou semer une pelouse, pousser l'applicateur",
    name_vtn: "Đi bộ, bón phân hoặc gieo hạt trên bãi cỏ, dụng cụ đẩy",
    met: 3,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Zāliena vai dārza laistīšana, stāvēšana vai pastaigas",
    name_eng: "Watering lawn or garden, standing or walking",
    name_ita: "Innaffiare il prato o il giardino, in piedi o camminando",
    name_esp: "Regar el césped o el jardín, de pie o caminando",
    name_fra: "Arroser la pelouse ou le jardin, debout ou en marchant",
    name_vtn: "Tưới cỏ hoặc vườn, đứng hoặc đi bộ",
    met: 1.5,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Ravēšana, dārza kopšana, viegla līdz mērena piepūle",
    name_eng: "Weeding, cultivating garden, light-to-moderate effort",
    name_ita: "Sarchiatura, coltivazione dell'orto, sforzo da leggero a moderato",
    name_esp: "Deshierbe, cultivo del jardín, esfuerzo ligero a moderado",
    name_fra: "Désherber, cultiver le jardin, effort léger à modéré",
    name_vtn: "Làm cỏ, xới vườn, gắng sức từ nhẹ đến trung bình",
    met: 3.5,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Ravēšana, dārza iekopšana",
    name_eng: "Weeding, cultivating garden (Taylor Code 580)",
    name_ita: "Sarchiatura, coltivazione giardino (Taylor Code 580)",
    name_esp: "Deshierbe, cultivo del jardín (Código Taylor 580)",
    name_fra: "Désherber, cultiver le jardin (Taylor Code 580)",
    name_vtn: "Làm cỏ, xới vườn (Taylor Code 580)",
    met: 4.5,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Ravēšana, dārza kultivēšana, kapļa izmantošana, mērena vai enerģiska piepūle",
    name_eng: "Weeding, cultivating garden, using a hoe, moderate-to-vigorous effort",
    name_ita: "Sarchiatura, coltivazione dell'orto, utilizzo della zappa, sforzo da moderato a vigoroso",
    name_esp: "Desyerbar, cultivar el jardín, usar una azada, esfuerzo de moderado a vigoroso",
    name_fra: "Désherber, cultiver le jardin, utiliser une houe, effort modéré à vigoureux",
    name_vtn: "Làm cỏ, xới vườn, dùng cuốc, gắng sức từ trung bình đến mạnh",
    met: 5,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Dārzkopība, vispārēja, mērena piepūle",
    name_eng: "Gardening, general, moderate effort",
    name_ita: "Giardinaggio, generale, sforzo moderato",
    name_esp: "Jardinería, general, esfuerzo moderado",
    name_fra: "Jardinage, général, effort modéré",
    name_vtn: "Làm vườn, nói chung, nỗ lực vừa phải",
    met: 3.8,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Augļu novākšana no kokiem, augļu/dārzeņu novākšana, mērena piepūle",
    name_eng: "Picking fruit off trees, picking fruits/vegetables, moderate effort",
    name_ita: "Raccogliere frutta dagli alberi, raccogliere frutta/verdura, sforzo moderato",
    name_esp: "Recoger frutas de los árboles, recoger frutas/verduras, esfuerzo moderado",
    name_fra: "Cueillir des fruits sur des arbres, cueillir des fruits/légumes, effort modéré",
    name_vtn: "Hái trái trên cây, hái trái/rau, sức vừa phải",
    met: 3.5,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Augļu novākšana no kokiem, augļu novākšana, augļu/dārzeņu novākšana, kāpšana pa kāpnēm augļu novākšanai, enerģiska piepūle",
    name_eng: "Picking fruit off trees, gleaning fruits, picking fruits/vegetables, climbing ladder to pick fruit, vigorous effort",
    name_ita: "Raccogliere frutta dagli alberi, spigolare frutta, raccogliere frutta/verdura, salire la scala per raccogliere frutta, sforzo vigoroso",
    name_esp: "Recoger frutas de los árboles, recoger frutas, recoger frutas/verduras, subir escaleras para recoger frutas, esfuerzo vigoroso",
    name_fra: "Cueillir des fruits sur les arbres, glaner des fruits, cueillir des fruits/légumes, monter à l'échelle pour cueillir des fruits, effort vigoureux",
    name_vtn: "Hái quả trên cây, mót quả, hái quả/rau, trèo thang để hái quả, gắng sức",
    met: 4.5,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Netieša staigāšana/stāvēšana - pagalma, gaismas ņemšana, ziedu vai dārzeņu lasīšana",
    name_eng: "Implied walking/standing - picking up yard, light, picking flowers or vegetables",
    name_ita: "Camminare / stare in piedi implicito: raccogliere il giardino, la luce, raccogliere fiori o verdure",
    name_esp: "Implícito caminar/de pie: recoger el jardín, la luz, recoger flores o vegetales",
    name_fra: "Marche/debout implicite - ramasser la cour, la lumière, cueillir des fleurs ou des légumes",
    name_vtn: "Ngụ ý đi/đứng - nhặt sân, đèn, hái hoa hoặc rau",
    met: 3.3,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Pastaigas, dārza rīku vākšana",
    name_eng: "Walking, gathering gardening tools",
    name_ita: "Camminare, raccogliere attrezzi da giardinaggio",
    name_esp: "Caminar, recolectar herramientas de jardinería.",
    name_fra: "Marcher, ramasser les outils de jardinage",
    name_vtn: "Đi bộ, thu thập dụng cụ làm vườn",
    met: 3,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Ķerra, stumt dārza ratiņus vai ķerru",
    name_eng: "Wheelbarrow, pushing garden cart or wheelbarrow",
    name_ita: "Carriola, carrello da giardino o carriola",
    name_esp: "Carretilla, empujando carro de jardín o carretilla",
    name_fra: "Brouette, chariot de jardin poussant ou brouette",
    name_vtn: "Xe cút kít, đẩy xe làm vườn hoặc xe cút kít",
    met: 5.5,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Pagalma darbs, vispārējs, viegls piepūle",
    name_eng: "Yard work, general, light effort",
    name_ita: "Lavoro in giardino, generale, sforzo leggero",
    name_esp: "Trabajo de jardinería, general, esfuerzo ligero",
    name_fra: "Travaux de jardinage, général, effort léger",
    name_vtn: "Công việc sân bãi, chung chung, nhẹ nhàng",
    met: 3,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Pagalma darbs, vispārējs, mērens piepūle",
    name_eng: "Yard work, general, moderate effort",
    name_ita: "Lavoro in giardino, sforzo generale, moderato",
    name_esp: "Trabajo en el jardín, general, esfuerzo moderado",
    name_fra: "Travaux de jardinage, général, effort modéré",
    name_vtn: "Công việc ngoài sân, nói chung, nỗ lực vừa phải",
    met: 4,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Pagalma darbs, vispārēja, enerģiska piepūle",
    name_eng: "Yard work, general, vigorous effort",
    name_ita: "Lavoro in giardino, sforzo generale e vigoroso",
    name_esp: "Trabajo en el jardín, general, esfuerzo vigoroso",
    name_fra: "Travaux de jardinage, général, effort vigoureux",
    name_vtn: "Công việc sân bãi, chung chung, nỗ lực mạnh mẽ",
    met: 6,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Galda spēļu spēlēšana, sēdēšana",
    name_eng: "Board game playing, sitting",
    name_ita: "Gioco da tavolo giocando, seduto",
    name_esp: "Juego de mesa, sentado",
    name_fra: "Jeu de société, assis",
    name_vtn: "Chơi trò chơi trên bàn, ngồi",
    met: 1.5,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Kazino azartspēles, stāvus",
    name_eng: "Casino gambling, standing",
    name_ita: "Gioco d'azzardo al casinò, in piedi",
    name_esp: "Juegos de casino, de pie",
    name_fra: "Jeu de casino, debout",
    name_vtn: "Sòng bạc đánh bạc, đứng",
    met: 2.5,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Kāršu spēlēšana, sēdēšana",
    name_eng: "Card playing, sitting",
    name_ita: "Giocare a carte, seduto",
    name_esp: "jugando a las cartas, sentado",
    name_fra: "Jouer aux cartes, assis",
    name_vtn: "chơi bài, ngồi",
    met: 1.5,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Šaha spēle, sēdēšana",
    name_eng: "Chess game, sitting",
    name_ita: "Partita a scacchi, seduta",
    name_esp: "Juego de ajedrez, sentado",
    name_fra: "Jeu d'échecs, assis",
    name_vtn: "Trò chơi cờ vua, ngồi",
    met: 1.5,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Dokumentu kopēšana, stāvēšana",
    name_eng: "Copying documents, standing",
    name_ita: "Copia di documenti, in piedi",
    name_esp: "Copia de documentos, de pie",
    name_fra: "Copier des documents, debout",
    name_vtn: "Sao chụp tài liệu đứng",
    met: 1.5,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Zīmēšana, rakstīšana, gleznošana, stāvēšana",
    name_eng: "Drawing, writing, painting, standing",
    name_ita: "Disegnare, scrivere, dipingere, stare in piedi",
    name_esp: "Dibujar, escribir, pintar, estar de pie",
    name_fra: "Dessiner, écrire, peindre, debout",
    name_vtn: "Vẽ, viết, sơn, đứng",
    met: 1.8,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Smejoties, sēžot",
    name_eng: "Laughing, sitting",
    name_ita: "Ridere, sedersi",
    name_esp: "riendo, sentado",
    name_fra: "Rire, assis",
    name_vtn: "Ngồi cười",
    met: 1,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Sēdēšana, lasīšana, grāmata, avīze utt.",
    name_eng: "Sitting, reading, book, newspaper, etc.",
    name_ita: "Seduto, lettura, libro, giornale, ecc.",
    name_esp: "Sentado, leyendo, libro, periódico, etc.",
    name_fra: "Assis, lecture, livre, journal, etc.",
    name_vtn: "Ngồi, đọc, sách, báo, v.v.",
    met: 1.3,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Sēdēšana, rakstīšana, darbs pie galda, rakstīšana",
    name_eng: "Sitting, writing, desk work, typing",
    name_ita: "Sedersi, scrivere, lavorare alla scrivania, digitare",
    name_esp: "Sentado, escribiendo, trabajo de escritorio, mecanografiando",
    name_fra: "Assis, écrit, travail de bureau, dactylographie",
    name_vtn: "Ngồi, viết, bàn làm việc, đánh máy",
    met: 1.3,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Sēžot, spēlējot tradicionālo video spēli, datorspēli",
    name_eng: "Sitting, playing traditional video game, computer game",
    name_ita: "Seduto, giocando a videogiochi tradizionali, giochi per computer",
    name_esp: "Sentado, jugando videojuegos tradicionales, juegos de computadora",
    name_fra: "Assis, jouant au jeu vidéo traditionnel, jeu d'ordinateur",
    name_vtn: "Ngồi, chơi trò chơi điện tử truyền thống, trò chơi máy tính",
    met: 1,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Stāvot, runājot klātienē, pa tālruni, datoru vai īsziņās, neliela piepūle",
    name_eng: "Standing, talking in person, on the phone, computer, or text messaging, light effort",
    name_ita: "Stare in piedi, parlare di persona, al telefono, al computer o inviare messaggi di testo, sforzo leggero",
    name_esp: "De pie, hablando en persona, por teléfono, computadora o mensajes de texto, esfuerzo ligero",
    name_fra: "Debout, parler en personne, au téléphone, à l'ordinateur ou par messagerie texte, effort léger",
    name_vtn: "Đứng, nói chuyện trực tiếp, trên điện thoại, máy tính hoặc nhắn tin, nỗ lực nhẹ",
    met: 1.8,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Sēžot, runājot klātienē, pa tālruni, datoru vai īsziņas, neliela piepūle",
    name_eng: "Sitting, talking in person, on the phone, computer, or text messaging, light effort",
    name_ita: "Sedersi, parlare di persona, al telefono, al computer o inviare messaggi di testo, sforzo leggero",
    name_esp: "Sentado, hablando en persona, por teléfono, computadora o mensajes de texto, esfuerzo ligero",
    name_fra: "Assis, parler en personne, au téléphone, à l'ordinateur ou par messagerie texte, effort léger",
    name_vtn: "Ngồi, nói chuyện trực tiếp, trên điện thoại, máy tính hoặc nhắn tin, nỗ lực nhẹ",
    met: 1.5,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Sēdēšana, mācīšanās, vispārēja, ieskaitot lasīšanu un/vai rakstīšanu, neliela piepūle",
    name_eng: "Sitting, studying, general, including reading and/or writing, light effort",
    name_ita: "Seduto, studio, generale, inclusa la lettura e/o la scrittura, sforzo leggero",
    name_esp: "Sentado, estudiando, general, incluyendo lectura y/o escritura, esfuerzo ligero",
    name_fra: "Assis, étudiant, général, y compris lecture et/ou écriture, effort léger",
    name_vtn: "Ngồi, học, nói chung, bao gồm đọc và/hoặc viết, gắng sức nhẹ",
    met: 1.3,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Sēžot, klasē, vispārīgi, ieskaitot piezīmju veikšanu vai klases diskusiju",
    name_eng: "Sitting, in class, general, including note-taking or class discussion",
    name_ita: "Seduto, in classe, generale, inclusa la presa di appunti o la discussione in classe",
    name_esp: "Sentado, en clase, general, incluida la toma de notas o la discusión en clase",
    name_fra: "Assis, en classe, général, y compris la prise de notes ou la discussion en classe",
    name_vtn: "Ngồi, trong lớp, nói chung, bao gồm ghi chép hoặc thảo luận trong lớp",
    met: 1.8,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Stāvot, lasīt",
    name_eng: "Standing, reading",
    name_ita: "In piedi, leggendo",
    name_esp: "de pie, leyendo",
    name_fra: "Debout, lecture",
    name_vtn: "Đứng, đọc",
    met: 1.8,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Stāvēšana, dažādi",
    name_eng: "Standing, miscellaneous",
    name_ita: "In piedi, varie",
    name_esp: "de pie, varios",
    name_fra: "Debout, divers",
    name_vtn: "Đứng, linh tinh",
    met: 2.5,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Sēdēšana, māksla un amatniecība, koka grebšana, aušana, vilnas vērpšana, viegla piepūle",
    name_eng: "Sitting, arts and crafts, carving wood, weaving, spinning wool, light effort",
    name_ita: "Sedersi, arti e mestieri, intagliare il legno, tessere, filare la lana, fatica leggera",
    name_esp: "Sentarse, artes y oficios, tallar madera, tejer, hilar lana, esfuerzo ligero",
    name_fra: "Assis, arts et artisanat, sculpture sur bois, tissage, filage de la laine, effort léger",
    name_vtn: "Ngồi, thủ công mỹ nghệ, chạm khắc gỗ, dệt vải, quay len, nhẹ nhàng",
    met: 1.8,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Sēdēšana, māksla un amatniecība, kokgriešana, aušana, vilnas vērpšana, mērena piepūle",
    name_eng: "Sitting, arts and crafts, carving wood, weaving, spinning wool, moderate effort",
    name_ita: "Sedersi, arti e mestieri, intagliare il legno, tessere, filare la lana, sforzo moderato",
    name_esp: "Sentarse, artes y oficios, tallar madera, tejer, hilar lana, esfuerzo moderado",
    name_fra: "Assis, arts et artisanat, sculpture sur bois, tissage, filage de la laine, effort modéré",
    name_vtn: "Ngồi, thủ công mỹ nghệ, chạm khắc gỗ, dệt vải, quay len, gắng sức vừa phải",
    met: 3,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Stāvēšana, māksla un amatniecība, smilšu krāsošana, grebšana, aušana, viegla piepūle",
    name_eng: "Standing, arts and crafts, sand painting, carving, weaving, light effort",
    name_ita: "In piedi, arti e mestieri, pittura con la sabbia, intaglio, tessitura, sforzo leggero",
    name_esp: "De pie, artes y oficios, pintura de arena, tallado, tejido, esfuerzo ligero",
    name_fra: "Debout, arts et artisanat, peinture sur sable, sculpture, tissage, effort léger",
    name_vtn: "Đứng, thủ công mỹ nghệ, vẽ tranh cát, chạm khắc, dệt vải, nhẹ nhàng",
    met: 2.5,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Stāvēšana, māksla un amatniecība, smilšu krāsošana, griešana, aušana, mērena piepūle",
    name_eng: "Standing, arts and crafts, sand painting, carving, weaving, moderate effort",
    name_ita: "In piedi, arti e mestieri, pittura con la sabbia, intaglio, tessitura, sforzo moderato",
    name_esp: "De pie, artes y oficios, pintar con arena, tallar, tejer, esfuerzo moderado",
    name_fra: "Debout, arts et artisanat, peinture sur sable, sculpture, tissage, effort modéré",
    name_vtn: "Đứng, nghệ thuật và thủ công, vẽ tranh cát, chạm khắc, dệt vải, nỗ lực vừa phải",
    met: 3.3,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Stāvēšana, māksla un amatniecība, smilšu krāsošana, griešana, aušana, enerģiska piepūle",
    name_eng: "Standing, arts and crafts, sand painting, carving, weaving, vigorous effort",
    name_ita: "In piedi, arti e mestieri, pittura con la sabbia, intaglio, tessitura, sforzo vigoroso",
    name_esp: "Estar de pie, artes y oficios, pintar con arena, tallar, tejer, esfuerzo vigoroso",
    name_fra: "Debout, arts et artisanat, peinture sur sable, sculpture, tissage, effort vigoureux",
    name_vtn: "Đứng, nghệ thuật và thủ công, vẽ tranh cát, chạm khắc, dệt vải, nỗ lực mạnh mẽ",
    met: 3.5,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Ģimenes atkalapvienošanās aktivitātes, kas ietver sēdēšanu, atpūtu, runāšanu, ēšanu",
    name_eng: "Retreat/family reunion activities involving sitting, relaxing, talking, eating",
    name_ita: "Attività di ritiro/ricongiungimento familiare che comportano sedersi, rilassarsi, parlare, mangiare",
    name_esp: "Actividades de retiro/reunión familiar que involucran sentarse, relajarse, hablar, comer",
    name_fra: "Activités de retraite / réunion de famille impliquant de s'asseoir, de se détendre, de parler, de manger",
    name_vtn: "Các hoạt động tĩnh tâm/đoàn tụ gia đình bao gồm ngồi, thư giãn, nói chuyện, ăn uống",
    met: 1.8,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Ģimenes atkalapvienošanās pasākumi, kas ietver spēļu spēlēšanu ar bērniem",
    name_eng: "Retreat/family reunion activities involving playing games with children",
    name_ita: "Attività di ritiro/ricongiungimento familiare che prevedono giochi con i bambini",
    name_esp: "Actividades de retiro/reunión familiar que involucran juegos con niños",
    name_fra: "Activités de retraite / réunion de famille impliquant des jeux avec les enfants",
    name_vtn: "Các hoạt động tĩnh tâm/đoàn tụ gia đình liên quan đến chơi trò chơi với trẻ em",
    met: 3,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Ceļošana/ceļošana/atvaļinājums, kas ietver braukšanu transportlīdzeklī",
    name_eng: "Touring/traveling/vacation involving riding in a vehicle",
    name_ita: "Touring/viaggi/vacanze che comportano la guida di un veicolo",
    name_esp: "Giras/viajes/vacaciones que implican viajar en un vehículo",
    name_fra: "Touring/voyage/vacances impliquant la conduite d'un véhicule",
    name_vtn: "Tham quan/du lịch/kỳ nghỉ liên quan đến việc đi xe",
    met: 2,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Ceļošana/ceļošana/atvaļinājums, kas ietver pastaigas",
    name_eng: "Touring/traveling/vacation involving walking",
    name_ita: "Touring/viaggi/vacanze che comportano il camminare",
    name_esp: "Giras/viajes/vacaciones que implican caminar",
    name_fra: "Touring/voyage/vacances impliquant la marche",
    name_vtn: "Tham quan/du lịch/kỳ nghỉ liên quan đến đi bộ",
    met: 3.5,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Kempings, kas ietver stāvēšanu, staigāšanu, sēdēšanu, vieglu vai mērenu piepūli",
    name_eng: "Camping involving standing, walking, sitting, light-to-moderate effort",
    name_ita: "Campeggio che comporta uno sforzo in piedi, camminata, seduta, da leggero a moderato",
    name_esp: "Acampar que implique estar de pie, caminar, sentarse, esfuerzo ligero a moderado",
    name_fra: "Camping impliquant debout, marchant, assis, effort léger à modéré",
    name_vtn: "Cắm trại liên quan đến đứng, đi, ngồi, nỗ lực từ nhẹ đến trung bình",
    met: 2.5,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Sēžu sporta pasākumā, skatītājs",
    name_eng: "Sitting at a sporting event, spectator",
    name_ita: "Seduto a un evento sportivo, spettatore",
    name_esp: "Sentado en un evento deportivo, espectador",
    name_fra: "Assis à un événement sportif, spectateur",
    name_vtn: "Ngồi tại một sự kiện thể thao, khán giả",
    met: 1.5,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Akordeons, sēdus",
    name_eng: "Accordion, sitting",
    name_ita: "Fisarmonica, seduto",
    name_esp: "acordeón, sentado",
    name_fra: "Accordéon, assis",
    name_vtn: "Đàn accordion, ngồi",
    met: 1.8,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Čells, sēž",
    name_eng: "Cello, sitting",
    name_ita: "Violoncello, seduto",
    name_esp: "violonchelo, sentado",
    name_fra: "violoncelle, assis",
    name_vtn: "Cello, ngồi",
    met: 2.3,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Orķestra diriģēšana, stāv",
    name_eng: "Conducting orchestra, standing",
    name_ita: "Direzione d'orchestra, in piedi",
    name_esp: "Orquesta de dirección, de pie",
    name_fra: "Direction d'orchestre, debout",
    name_vtn: "Chỉ huy dàn nhạc đứng",
    met: 2.3,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Kontrabass, stāvus",
    name_eng: "Double bass, standing",
    name_ita: "Contrabbasso, in piedi",
    name_esp: "Contrabajo, de pie",
    name_fra: "Contrebasse, debout",
    name_vtn: "Đôi bass, đứng",
    met: 2.5,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Bungas, sēdēšana",
    name_eng: "Drums, sitting",
    name_ita: "Tamburi, seduti",
    name_esp: "tambores, sentado",
    name_fra: "Batterie, assis",
    name_vtn: "Trống, ngồi",
    met: 3.8,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Bungošana (piemēram, bongo, konga, benbe), mērena, sēdus",
    name_eng: "Drumming (e.g., bongo, conga, benbe), moderate, sitting",
    name_ita: "Suonare la batteria (ad es. bongo, conga, benbe), moderato, seduto",
    name_esp: "Percusión (p. ej., bongo, conga, benbe), moderado, sentado",
    name_fra: "Tambour (par exemple, bongo, conga, benbe), modéré, assis",
    name_vtn: "Đánh trống (ví dụ: bongo, conga, benbe), vừa phải, ngồi",
    met: 3,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Flauta, sēž",
    name_eng: "Flute, sitting",
    name_ita: "Flauto, seduto",
    name_esp: "flauta, sentado",
    name_fra: "Flûte, assis",
    name_vtn: "Sáo, ngồi",
    met: 2,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Rags, stāv",
    name_eng: "Horn, standing",
    name_ita: "Corno, in piedi",
    name_esp: "cuerno, de pie",
    name_fra: "Corne, debout",
    name_vtn: "Sừng, đứng",
    met: 1.8,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Klavieres, sēdus",
    name_eng: "Piano, sitting",
    name_ita: "Pianoforte, seduto",
    name_esp: "piano, sentado",
    name_fra: "Piano, assis",
    name_vtn: "Piano, ngồi",
    met: 2.3,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Mūzikas instrumentu spēle, vispār",
    name_eng: "Playing musical instruments, general",
    name_ita: "Suonare strumenti musicali, generale",
    name_esp: "Tocar instrumentos musicales, general",
    name_fra: "Jouer des instruments de musique, général",
    name_vtn: "Chơi nhạc cụ, nói chung",
    met: 2,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Ērģeles, sēdēšana",
    name_eng: "Organ, sitting",
    name_ita: "Organo, seduta",
    name_esp: "órgano, sentado",
    name_fra: "Orgue, assis",
    name_vtn: "đàn organ, ngồi",
    met: 2,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Trombons, stāvus",
    name_eng: "Trombone, standing",
    name_ita: "Trombone, in piedi",
    name_esp: "trombón, de pie",
    name_fra: "Trombone, debout",
    name_vtn: "Trombone, đứng",
    met: 3.5,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Trompete, stāv",
    name_eng: "Trumpet, standing",
    name_ita: "Tromba, in piedi",
    name_esp: "trompeta, de pie",
    name_fra: "Trompette, debout",
    name_vtn: "Trumpet, đứng",
    met: 1.8,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Vijole, sēž",
    name_eng: "Violin, sitting",
    name_ita: "Violino, seduto",
    name_esp: "violín, sentado",
    name_fra: "violon, assis",
    name_vtn: "Violon, ngồi",
    met: 2.5,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Koka pūšaminstruments, sēdēšana",
    name_eng: "Woodwind, sitting",
    name_ita: "Legni, seduto",
    name_esp: "Instrumento de viento de madera, sentado",
    name_fra: "Bois, assis",
    name_vtn: "Woodwind, ngồi",
    met: 1.8,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Ģitāra, klasika, folks, sēdus",
    name_eng: "Guitar, classical, folk, sitting",
    name_ita: "Chitarra, classica, folk, seduta",
    name_esp: "Guitarra, clásica, folk, sentado",
    name_fra: "Guitare, classique, folk, assis",
    name_vtn: "Guitar, cổ điển, dân gian, ngồi",
    met: 2,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Ģitāra, rokenrola grupa, stāvus",
    name_eng: "Guitar, rock and roll band, standing",
    name_ita: "Chitarra, rock and roll band, in piedi",
    name_esp: "Guitarra, banda de rock and roll, de pie",
    name_fra: "Guitare, groupe de rock and roll, debout",
    name_vtn: "Guitar, ban nhạc rock and roll, đứng",
    met: 3,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Maršēšanas grupa, stafetes virpošana, soļošana, mērens temps, ģenerālis",
    name_eng: "Marching band, baton twirling, walking, moderate pace, general",
    name_ita: "Banda musicale, rotazione del bastone, camminata, andatura moderata, generale",
    name_esp: "Banda de música, batuta, caminar, paso moderado, general",
    name_fra: "Fanfare, tour de bâton, marche, allure modérée, général",
    name_vtn: "Ban nhạc diễu hành, xoay dùi cui, đi bộ, tốc độ vừa phải, chung",
    met: 4,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Maršgrupa, instrumenta spēle, soļošana, ātrā solī, ģenerālis",
    name_eng: "Marching band, playing an instrument, walking, brisk pace, general",
    name_ita: "Fanfara, suonare uno strumento, camminare, passo svelto, generale",
    name_esp: "Banda de marcha, tocar un instrumento, caminar, paso rápido, general",
    name_fra: "Fanfare, jouer d'un instrument, marcher, rythme rapide, général",
    name_vtn: "Ban nhạc diễu hành, chơi nhạc cụ, đi bộ, tốc độ nhanh, nói chung",
    met: 5.5,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Maršgrupa, bungu majors, soļošana",
    name_eng: "Marching band, drum major, walking",
    name_ita: "Banda musicale, tamburo maggiore, marcia",
    name_esp: "Banda de marcha, tambor mayor, caminando",
    name_fra: "Fanfare, tambour-major, marche",
    name_vtn: "Ban nhạc diễu hành, trống trưởng, đi bộ",
    met: 3.5,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Aktīva, enerģiskas pūles",
    name_eng: "Active, vigorous effort",
    name_ita: "Sforzo attivo e vigoroso",
    name_esp: "Esfuerzo activo y vigoroso",
    name_fra: "Effort actif et vigoureux",
    name_vtn: "Nỗ lực tích cực, mạnh mẽ",
    met: 2.8,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Vispārēja, mērena piepūle",
    name_eng: "General, moderate effort",
    name_ita: "Sforzo generale e moderato",
    name_esp: "Esfuerzo general moderado",
    name_fra: "Général, effort modéré",
    name_vtn: "Nỗ lực chung, vừa phải",
    met: 1.8,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Pasīva, viegla piepūle, skūpstīšanās, apskaušanās",
    name_eng: "Passive, light effort, kissing, hugging",
    name_ita: "Passivo, sforzo leggero, baci, abbracci",
    name_esp: "Pasivo, esfuerzo ligero, besos, abrazos.",
    name_fra: "Passif, effort léger, baisers, câlins",
    name_vtn: "Thụ động, nỗ lực nhẹ, hôn, ôm",
    met: 1.3,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Sēžot baznīcā, dievkalpojumā, apmeklējot ceremoniju, sēžot klusi",
    name_eng: "Sitting in church, in service, attending a ceremony, sitting quietly",
    name_ita: "Seduto in chiesa, in servizio, partecipando a una cerimonia, seduto in silenzio",
    name_esp: "Sentado en la iglesia, en el servicio, asistiendo a una ceremonia, sentado en silencio",
    name_fra: "Assis à l'église, en service, assistant à une cérémonie, assis tranquillement",
    name_vtn: "Ngồi trong nhà thờ, phục vụ, dự lễ, ngồi yên lặng",
    met: 1.3,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Sēžu, spēlē kādu instrumentu baznīcā",
    name_eng: "Sitting, playing an instrument at church",
    name_ita: "Seduto, suonando uno strumento in chiesa",
    name_esp: "Sentado, tocando un instrumento en la iglesia",
    name_fra: "Assis, jouant d'un instrument à l'église",
    name_vtn: "Ngồi chơi nhạc cụ trong nhà thờ",
    met: 2,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Sēdēšana baznīcā, runāšana vai dziedāšana, ceremonijas apmeklēšana, sēdēšana, aktīva līdzdalība",
    name_eng: "Sitting in church, talking or singing, attending a ceremony, sitting, active participation",
    name_ita: "Sedersi in chiesa, parlare o cantare, assistere a una cerimonia, sedersi, partecipare attivamente",
    name_esp: "Sentado en la iglesia, hablando o cantando, asistiendo a una ceremonia, sentado, participación activa",
    name_fra: "Être assis à l'église, parler ou chanter, assister à une cérémonie, s'asseoir, participer activement",
    name_vtn: "Ngồi trong nhà thờ, nói chuyện hoặc ca hát, tham dự một buổi lễ, ngồi, tham gia tích cực",
    met: 1.8,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Sēžot, lasot reliģiskus materiālus mājās",
    name_eng: "Sitting, reading religious materials at home",
    name_ita: "Sedersi, leggere materiale religioso a casa",
    name_esp: "Sentado, leyendo materiales religiosos en casa",
    name_fra: "Assis, lisant des documents religieux à la maison",
    name_vtn: "Ngồi, đọc tài liệu tôn giáo ở nhà",
    met: 1.3,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Klusi stāvot baznīcā, apmeklējot ceremoniju",
    name_eng: "Standing quietly in church, attending a ceremony",
    name_ita: "In piedi in silenzio in chiesa, partecipando a una cerimonia",
    name_esp: "De pie en silencio en la iglesia, asistiendo a una ceremonia",
    name_fra: "Se tenir tranquillement à l'église, assister à une cérémonie",
    name_vtn: "Đứng lặng lẽ trong nhà thờ, tham dự một buổi lễ",
    met: 1.3,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Stāvēšana, dziedāšana baznīcā, ceremonijas apmeklēšana, stāvēšana, aktīva līdzdalība",
    name_eng: "Standing, singing in church, attending a ceremony, standing, active participation",
    name_ita: "Stare in piedi, cantare in chiesa, assistere a una cerimonia, stare in piedi, partecipazione attiva",
    name_esp: "De pie, cantando en la iglesia, asistiendo a una ceremonia, de pie, participación activa",
    name_fra: "Se tenir debout, chanter à l'église, assister à une cérémonie, se tenir debout, participer activement",
    name_vtn: "Đứng, hát trong nhà thờ, dự lễ, đứng, tham gia tích cực",
    met: 2,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Ceļos baznīcā vai mājās, lūgšana",
    name_eng: "Kneeling in church or at home, praying",
    name_ita: "In ginocchio in chiesa oa casa, a pregare",
    name_esp: "De rodillas en la iglesia o en casa, orando",
    name_fra: "S'agenouiller à l'église ou à la maison, prier",
    name_vtn: "Quỳ trong nhà thờ hoặc ở nhà, cầu nguyện",
    met: 1.3,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Stāvam, runājam baznīcā",
    name_eng: "Standing, talking in church",
    name_ita: "In piedi, parlando in chiesa",
    name_esp: "De pie, hablando en la iglesia",
    name_fra: "Debout, parlant à l'église",
    name_vtn: "Đứng nói chuyện trong nhà thờ",
    met: 1.8,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Pastaiga baznīcā",
    name_eng: "Walking in church",
    name_ita: "Camminare in chiesa",
    name_esp: "caminando en la iglesia",
    name_fra: "Marcher dans l'église",
    name_vtn: "Đi bộ trong nhà thờ",
    met: 2,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Ejot, mazāk nekā 3,2 km/h, ļoti lēni",
    name_eng: "Walking, less than 3.2 km/h, very slow",
    name_ita: "Camminare, meno di 3,2 km/h, molto lento",
    name_esp: "Caminando, menos de 3,2 km/h, muy lento",
    name_fra: "Marche, moins de 3,2 km/h, très lente",
    name_vtn: "Đi bộ, dưới 3,2 km/h, rất chậm",
    met: 2,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Ejot, 4,8 km/h, mērens ātrums, neko nenesot",
    name_eng: "Walking, 4.8 km/h, moderate speed, not carrying anything",
    name_ita: "Camminare, 4,8 km/h, velocità moderata, senza trasportare nulla",
    name_esp: "Andando, 4,8 km/h, velocidad moderada, sin llevar nada",
    name_fra: "Marche, 4,8 km/h, vitesse modérée, ne portant rien",
    name_vtn: "Đi bộ, 4,8 km/h, tốc độ vừa phải, không mang theo gì",
    met: 3.5,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Ejot, 5,6 km/h, liels ātrums, neko nenesot",
    name_eng: "Walking, 5.6 km/h, brisk speed, not carrying anything",
    name_ita: "Camminare, 5,6 km/h, velocità sostenuta, senza trasportare nulla",
    name_esp: "Caminando, 5,6 km/h, velocidad rápida, sin llevar nada",
    name_fra: "Marche, 5,6 km/h, vitesse rapide, ne portant rien",
    name_vtn: "Đi bộ, 5,6 km/h, tốc độ nhanh, không mang theo bất cứ thứ gì",
    met: 4.3,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Pastaigu/stāvu kombinācija reliģiskiem nolūkiem, vedējs",
    name_eng: "Walk/stand combination for religious purposes, usher",
    name_ita: "Combinazione camminata/stand per scopi religiosi, usciere",
    name_esp: "Combinación de caminar/pararse con fines religiosos, ujier",
    name_fra: "Combinaison marche/debout à des fins religieuses, huissier",
    name_vtn: "Đi bộ/đứng kết hợp cho mục đích tôn giáo, mở ra",
    met: 2,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Slavēšana ar deju vai skriešanu, garīgās dejas baznīcā",
    name_eng: "Praise with dance or run, spiritual dancing in church",
    name_ita: "Lode con danza o corsa, danza spirituale in chiesa",
    name_esp: "Alabanza con baile o carrera, baile espiritual en la iglesia",
    name_fra: "Louange avec danse ou course, danse spirituelle à l'église",
    name_vtn: "Ca ngợi bằng khiêu vũ hoặc chạy, khiêu vũ tâm linh trong nhà thờ",
    met: 5,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Ēdienu pasniegšana baznīcā",
    name_eng: "Serving food at church",
    name_ita: "Servire il cibo in chiesa",
    name_esp: "sirviendo comida en la iglesia",
    name_fra: "Servir à manger à l'église",
    name_vtn: "Phục vụ thức ăn tại nhà thờ",
    met: 2.5,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Ēdiena gatavošana baznīcā",
    name_eng: "Preparing food at church",
    name_ita: "Preparare il cibo in chiesa",
    name_esp: "Preparando comida en la iglesia",
    name_fra: "Préparer la nourriture à l'église",
    name_vtn: "Chuẩn bị thức ăn tại nhà thờ",
    met: 2,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Trauku mazgāšana, virtuves uzkopšana baznīcā",
    name_eng: "Washing dishes, cleaning kitchen at church",
    name_ita: "Lavare i piatti, pulire la cucina in chiesa",
    name_esp: "Lavar los platos, limpiar la cocina en la iglesia",
    name_fra: "Laver la vaisselle, nettoyer la cuisine à l'église",
    name_vtn: "Rửa bát, lau bếp nhà thờ",
    met: 3.3,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Ēšana baznīcā",
    name_eng: "Eating at church",
    name_ita: "Mangiare in chiesa",
    name_esp: "comiendo en la iglesia",
    name_fra: "Manger à l'église",
    name_vtn: "Ăn ở nhà thờ",
    met: 1.5,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Ēšana/runāšana baznīcā vai stāvēšana, Amerikas indiāņu svētku dienas",
    name_eng: "Eating/talking at church or standing eating, American Indian Feast days",
    name_ita: "Mangiare/parlare in chiesa o mangiare in piedi, giorni di festa degli indiani d'America",
    name_esp: "Comer/hablar en la iglesia o comer de pie, días festivos de los indios americanos",
    name_fra: "Manger/parler à l'église ou manger debout, jours de fête des Indiens d'Amérique",
    name_vtn: "Ăn/nói chuyện ở nhà thờ hoặc đứng ăn, ngày lễ của người Mỹ da đỏ",
    met: 2,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Baznīcas tīrīšana",
    name_eng: "Cleaning church",
    name_ita: "Chiesa di pulizia",
    name_esp: "iglesia de limpieza",
    name_fra: "Nettoyage de l'église",
    name_vtn: "Dọn dẹp nhà thờ",
    met: 3.3,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Vispārējie pagalma darbi baznīcā",
    name_eng: "General yard work at church",
    name_ita: "Lavori generali in cantiere in chiesa",
    name_esp: "Trabajo general de jardinería en la iglesia",
    name_fra: "Travaux généraux de jardinage à l'église",
    name_vtn: "Làm sân chung tại nhà thờ",
    met: 4,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Stāvēšana, mērena piepūle (piemēram, smagu priekšmetu celšana, ātra salikšana)",
    name_eng: "Standing, moderate effort (e.g., lifting heavy objects, assembling at fast rate)",
    name_ita: "Stare in piedi, sforzo moderato (per es., sollevare oggetti pesanti, montare velocemente)",
    name_esp: "De pie, esfuerzo moderado (p. ej., levantar objetos pesados, montar a gran velocidad)",
    name_fra: "Debout, effort modéré (par exemple, soulever des objets lourds, assembler à un rythme rapide)",
    name_vtn: "Đứng, nỗ lực vừa phải (ví dụ: nâng vật nặng, lắp ráp với tốc độ nhanh)",
    met: 3.5,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Stāvēšana, vidēja līdz smaga piepūle, roku darbs, celšana ≥ 22kg, smaga apkope",
    name_eng: "Standing, moderate-to-heavy effort, manual labor, lifting ≥ 22kg, heavy maintenance",
    name_ita: "In piedi, sforzo da moderato a pesante, lavoro manuale, sollevamento ≥ 22 kg, manutenzione pesante",
    name_esp: "De pie, esfuerzo de moderado a pesado, trabajo manual, levantar ≥ 22 kg, mantenimiento pesado",
    name_fra: "Debout, effort modéré à lourd, travail manuel, levage ≥ 22 kg, entretien lourd",
    name_vtn: "Đứng, gắng sức vừa đến nặng, lao động chân tay, nâng vật nặng ≥ 22kg, bảo trì nặng",
    met: 4.5,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Mašīnrakstīšanas, elektriskā, manuālā vai datora",
    name_eng: "Typing, electric, manual, or computer",
    name_ita: "Dattilografia, elettrico, manuale o computer",
    name_esp: "Mecanografía, eléctrica, manual o informática",
    name_fra: "Dactylographie, électrique, manuelle ou informatique",
    name_vtn: "Đánh máy, điện, thủ công hoặc máy tính",
    met: 1.3,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Sēdēšana sapulcē, vispārīgi un/vai ar sarunu",
    name_eng: "Sitting, meeting, general, and/or with talking involved",
    name_ita: "Seduto, incontro, generale e/o con conversazione coinvolta",
    name_esp: "Sentado, reunión, general y/o con hablar involucrado",
    name_fra: "Assis, réunion, général et/ou avec conversation impliquée",
    name_vtn: "Ngồi, họp, nói chung và/hoặc có liên quan đến nói chuyện",
    met: 1.5,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Sēdēšana, viegls biroja darbs, vispārīgi",
    name_eng: "Sitting, light office work, in general",
    name_ita: "Seduto, lavoro d'ufficio leggero, in generale",
    name_esp: "Sentado, trabajo ligero de oficina, en general",
    name_fra: "Assis, travail de bureau léger, en général",
    name_vtn: "Ngồi văn phòng, công việc nhẹ nhàng, nói chung",
    met: 1.5,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Sēdēšana, mērens darbs",
    name_eng: "Sitting, moderate work",
    name_ita: "Seduto, lavoro moderato",
    name_esp: "Sentado, trabajo moderado",
    name_fra: "Assis, travail modéré",
    name_vtn: "Ngồi làm việc vừa phải",
    met: 2.5,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Stāvēšana, viegls darbs (iekārtošana, runāšana, montāža)",
    name_eng: "Standing, light work (filing, talking, assembling)",
    name_ita: "In piedi, lavoro leggero (archiviare, parlare, assemblare)",
    name_esp: "De pie, trabajo ligero (archivar, hablar, ensamblar)",
    name_fra: "Debout, travaux légers (classer, parler, assembler)",
    name_vtn: "Đứng, công việc nhẹ nhàng (dập hồ sơ, nói chuyện, lắp ráp)",
    met: 2.3,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Sēdēšana, bērnu aprūpe, tikai aktīvi periodi",
    name_eng: "Sitting, child care, only active periods",
    name_ita: "Seduto, assistenza all'infanzia, solo periodi attivi",
    name_esp: "Sentado, cuidado de niños, solo períodos activos",
    name_fra: "Assis, garde d'enfants, uniquement les périodes actives",
    name_vtn: "Ngồi, chăm sóc trẻ em, chỉ có thời gian hoạt động",
    met: 2,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Stāvēšana, bērnu aprūpe, tikai aktīvi periodi",
    name_eng: "Standing, child care, only active periods",
    name_ita: "In piedi, assistenza all'infanzia, solo periodi attivi",
    name_esp: "De pie, cuidado de niños, solo periodos activos",
    name_fra: "Debout, garde d'enfants, seulement périodes actives",
    name_vtn: "Thường trực, chăm sóc trẻ em, chỉ có thời gian hoạt động",
    met: 3,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Staigāt/skriet rotaļās ar bērniem, mēreni, tikai aktīvi periodi",
    name_eng: "Walk/run play with children, moderate, only active periods",
    name_ita: "Camminare/correre giocare con i bambini, moderati, solo periodi attivi",
    name_esp: "Caminar/correr jugar con niños, moderado, solo períodos activos",
    name_fra: "Marcher/courir avec les enfants, modéré, périodes actives uniquement",
    name_vtn: "Đi bộ/chạy chơi với trẻ, vừa phải, chỉ trong thời gian hoạt động",
    met: 3.5,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Staigāt/skriet rotaļās ar bērniem, enerģiski, tikai aktīvi periodi",
    name_eng: "Walk/run play with children, vigorous, only active periods",
    name_ita: "Cammina / corri gioca con i bambini, vigoroso, solo periodi attivi",
    name_esp: "Caminar/correr jugar con niños, vigoroso, solo períodos activos",
    name_fra: "Marcher/courir avec les enfants, vigoureux, périodes actives uniquement",
    name_vtn: "Đi bộ/chạy chơi với trẻ em, mạnh mẽ, chỉ thời gian hoạt động",
    met: 5.8,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Stāvēšana, viegls/mērens darbs (piem., iesaiņot kastes, salikt/remontēt, uzstādīt krēslus/mēbeles)",
    name_eng: "Standing, light/moderate work (e.g., pack boxes, assemble/repair, set up chairs/furniture)",
    name_ita: "Lavoro in piedi, leggero/moderato (ad esempio, imballare scatole, assemblare/riparare, sistemare sedie/mobili)",
    name_esp: "Trabajo ligero/moderado de pie (p. ej., empacar cajas, ensamblar/reparar, instalar sillas/muebles)",
    name_fra: "Travail debout, léger/modéré (par exemple, emballer des cartons, assembler/réparer, installer des chaises/meubles)",
    name_vtn: "Công việc đứng, nhẹ/vừa phải (ví dụ: đóng gói hộp, lắp ráp/sửa chữa, kê ghế/đồ nội thất)",
    met: 3,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Stāvēšana, mēreni (paceļot 22kg, saliekot ātri)",
    name_eng: "Standing, moderate (lifting 22kg, assembling at fast rate)",
    name_ita: "In piedi, moderato (sollevamento di 22 kg, montaggio rapido)",
    name_esp: "De pie, moderado (levantar 22 kg, ensamblar a un ritmo rápido)",
    name_fra: "Debout, modéré (levage de 22 kg, assemblage rapide)",
    name_vtn: "Đứng, vừa phải (nâng 22kg, lắp ráp nhanh)",
    met: 3.5,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Stāvēšana, mērens/smags darbs",
    name_eng: "Standing, moderate/heavy work",
    name_ita: "Lavoro in piedi, moderato/pesante",
    name_esp: "De pie, trabajo moderado/pesado",
    name_fra: "Travail debout, modéré/lourd",
    name_vtn: "Công việc đứng, vừa/nặng",
    met: 4.5,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Mašīnrakstīšanas, elektriskā, manuālā vai datora",
    name_eng: "Typing, electric, manual, or computer",
    name_ita: "Dattilografia, elettrico, manuale o computer",
    name_esp: "Mecanografía, eléctrica, manual o informática",
    name_fra: "Dactylographie, électrique, manuelle ou informatique",
    name_vtn: "Đánh máy, điện, thủ công hoặc máy tính",
    met: 1.3,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Iešana, mazāk nekā 3,2 km/h, ļoti lēni",
    name_eng: "Walking, less than 3,2 km/h, very slow",
    name_ita: "Camminare, meno di 3,2 km/h, molto lento",
    name_esp: "Andando, menos de 3,2 km/h, muy lento",
    name_fra: "Marche, moins de 3,2 km/h, très lente",
    name_vtn: "Đi bộ, dưới 3,2 km/h, rất chậm",
    met: 2,
    cluster: 1,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Iešana, 4,8 km/h, mērens ātrums, neko nenesot",
    name_eng: "Walking, 4,8 km/h, moderate speed, not carrying anything",
    name_ita: "Camminare, 4,8 km/h, velocità moderata, senza trasportare nulla",
    name_esp: "Andando, 4,8 km/h, velocidad moderada, sin llevar nada",
    name_fra: "Marche, 4,8 km/h, vitesse modérée, ne portant rien",
    name_vtn: "Đi bộ, 4,8 km/h, tốc độ vừa phải, không mang theo gì",
    met: 3.5,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Iešana, 5,6 km/h, liels ātrums, neko nenesot",
    name_eng: "Walking, 5,6 km/h, brisk speed, not carrying anything",
    name_ita: "Camminare, 5,6 km/h, velocità sostenuta, senza trasportare nulla",
    name_esp: "Andando, 5,6 km/h, velocidad rápida, sin llevar nada",
    name_fra: "Marche, 5,6 km/h, vitesse rapide, ne portant rien",
    name_vtn: "Đi bộ, 5,6 km/h, tốc độ nhanh, không mang theo bất cứ thứ gì",
    met: 4.3,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Iešana, 4 km/h lēni un nesot priekšmetus, kas mazāki par 11kg",
    name_eng: "Walking, 4 km/h slowly and carrying objects less than 11kg",
    name_ita: "Camminare, 4 km/h lentamente e trasportare oggetti di peso inferiore a 11 kg",
    name_esp: "Caminar, 4 km/h despacio y llevar objetos de menos de 11 kg",
    name_fra: "Marcher à 4 km/h lentement et porter des objets de moins de 11 kg",
    name_vtn: "Đi bộ, đi chậm 4 km/h và mang vật có khối lượng dưới 11kg",
    met: 3.5,
    cluster: 2,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Iešana, mēreni 4,8 km/h un nesot priekšmetus, kas mazāki par 11kg, kaut ko stumjot",
    name_eng: "Walking, 4,8 km/h moderately and carrying objects less than 11kg, pushing something",
    name_ita: "Camminare, 4,8 km/h moderatamente e trasportare oggetti di peso inferiore a 11 kg, spingere qualcosa",
    name_esp: "Caminar, 4,8 km/h moderadamente y llevar objetos de menos de 11 kg, empujar algo",
    name_fra: "Marcher, 4,8 km/h modérément et porter des objets de moins de 11kg, pousser quelque chose",
    name_vtn: "Đi bộ, vừa phải 4,8 km/h và mang vật nhẹ hơn 11kg, đẩy vật",
    met: 4.5,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Iešana, 5,6 km/h, ņipri un nesot priekšmetus, kas mazāki par 11kg",
    name_eng: "Walking, 5,6 km/h, briskly and carrying objects less than 11kg",
    name_ita: "Camminare, 5,6 km/h, a passo svelto e trasportare oggetti di peso inferiore a 11 kg",
    name_esp: "Caminar, 5,6 km/h, a paso ligero y llevar objetos de menos de 11 kg",
    name_fra: "Marcher, 5,6 km/h, d'un bon pas et porter des objets de moins de 11kg",
    name_vtn: "Đi bộ, 5,6 km/h, nhanh và mang vật nhẹ hơn 11kg",
    met: 4.8,
    cluster: 3,
    category: "Brīvais laiks"
  },
  {
    name_lat: "Staigāšanas/stāvēšanas kombinācija brīvprātīgo vajadzībām",
    name_eng: "Walk/stand combination, for volunteer purposes",
    name_ita: "Combinazione camminata/stand, per scopi di volontariato",
    name_esp: "Combinación de caminar/pararse, para fines voluntarios",
    name_fra: "Combinaison marche/debout, à des fins bénévoles",
    name_vtn: "Đi bộ/đứng kết hợp, cho mục đích tình nguyện",
    met: 3,
    cluster: 2,
    category: "Brīvais laiks"
  }
];
